server:
  port: 9080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=project3
    username: postgres
    password: 
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate